# Generated by Django 4.2 on 2023-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='selected_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
